#!/bin/bash -ex

[[ -z "$FAB_HTTP_PROXY" ]] || export http_proxy=$FAB_HTTP_PROXY
[[ -z "$FAB_HTTPS_PROXY" ]] || export https_proxy=$FAB_HTTPS_PROXY

WEBROOT=/var/www/tracks
REPO=TracksApp/tracks

# nuke preconfigured tracks app (from common/conf/rails)
rm -rf $WEBROOT

# following the lead of others, versioned release is quite dated & master
# includes some sec updates - so cloning from that.
git clone --depth=1 https://github.com/$REPO.git $WEBROOT
