#!/bin/bash -ex

[[ -z "$FAB_HTTP_PROXY" ]] || export http_proxy=$FAB_HTTP_PROXY
[[ -z "$FAB_HTTPS_PROXY" ]] || export https_proxy=$FAB_HTTPS_PROXY

WEBROOT=/var/www/tracks
REPO=TracksApp/tracks

ls -la $(dirname $WEBROOT)
ls -la $WEBROOT

# following the lead of others, version release is quite dated & master
# includes some sec updates - so installing from that...
#VERSION=$(gh_releases $REPO | grep -vi "rc" | sort -V | tail -1)
#git clone --depth=1 --branch=$VERSION https://github.com/$REPO.git $WEBROOT
git clone --depth=1 https://github.com/$REPO.git $WEBROOT
