#!/bin/bash -ex

ADMIN_NAME=admin
ADMIN_PASS=turnkey1
# current tracks expects DB named 'tracks'
DB_NAME=tracks
DB_USER=tracks
DB_PASS=$(mcookie)
WEBROOT=/var/www/tracks

# start mysql
service mysql start

# use default config template
cp $WEBROOT/config/site.yml.tmpl $WEBROOT/config/site.yml

# tracks default config uses DB 'tracks' so let's create that, the user and
# remove DBs created by common/conf/rails
mysqladmin create $DB_NAME
mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* \
          to $DB_USER@localhost IDENTIFIED BY '$DB_PASS'; \
          flush privileges;"
for db in development production test; do
    mysqladmin --force drop ${DB_NAME}_$db
done

# configure db conf template
mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* \
          to $DB_USER@localhost IDENTIFIED BY '$DB_PASS'; \
          flush privileges;"
cp $WEBROOT/config/database.yml.tmpl $WEBROOT/config/database.yml
sed -i "\|encoding: utf8|s|# *||; \
        \|username: |s|:.*|: $DB_USER|; \
        \|password:|s|:.*|: $DB_PASS|" \
       $WEBROOT/config/database.yml

cd $WEBROOT
rm .ruby-version

# fix broken dep - see https://github.com/TracksApp/tracks/blob/ruby31/Gemfile#L32
sed -i "\|^gem 'therubyracer',|s|'therubyracer'|'mini_racer'|" Gemfile

# install
export RAILS_ENV=production
bundle config set --local path 'vendor/bundle'
bundle config set --local without 'development test postgresql sqlite'
bundle update # probably should be 'install' but that is currently failing!?
bundle exec rake db:migrate

# configure file structure & permissions
rm -f $WEBROOT/log/*
mkdir -p $WEBROOT/tmp/cache \
         $WEBROOT/public/uploads/csv \
         $WEBROOT/log \
         /var/log/tracks
mv $WEBROOT/log/* /var/log/tracks/
ln -s /var/log/tracks $WEBROOT/log
chown -R www-data:www-data $WEBROOT/tmp \
                           $WEBROOT/public/uploads \
                           $WEBROOT/log \
                           /var/log/tracks
chmod 666 /var/log/tracks/*

# precompile assets
bundle exec rake assets:precompile

# turnkey-credit (passenger substitute x2 bug)
cat >>$WEBROOT/app/assets/stylesheets/tracks.css.scss<<EOF
#turnkey-credit {
    font-family: Tahoma,Sans,Arial,Helvetica,Verdana,sans-serif;
    font-size: 11px;
    text-align: center;
    padding-top: 5px;
}
#turnkey-credit a {
    text-decoration: none;
}
EOF

TURNKEY_CREDIT="<div id='turnkey-credit'> <div> <a href='https://www.turnkeylinux.org/tracks'>Tracks Appliance</a> - Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a> </div> </div>"

FOOTER=$WEBROOT/app/views/shared/_footer.html.erb
sed -i "s|</div>|$TURNKEY_CREDIT\n</div>|" $FOOTER

service apache2 start

sleep 5

# create admin user & init app settings
TOKEN=$( curl -c /tmp/cookies.txt -s http://localhost/signup \
        | grep -o '<input type="hidden" name="authenticity_token" .* />' \
        | grep -o 'value=".*"' \
        | grep -o '".*"' \
        | tr -d \" )
curl -s -X POST -b /tmp/cookies.txt http://localhost/users \
        --data-urlencode "utf8=✓" \
        --data-urlencode "authenticity_token=${TOKEN}" \
        --data-urlencode "user%5Blogin%5D=${ADMIN_NAME}" \
        --data-urlencode "user%5Bpassword%5D=${ADMIN_PASS}" \
        --data-urlencode "user%5Bpassword_confirmation%5D=${ADMIN_PASS}"

rm -f /tmp/cookies.txt

# stop mariadb & apache2
service mariadb stop
service apache2 stop
