#!/bin/bash -ex

ADMIN_NAME=admin
ADMIN_PASS=turnkey1
DB_NAME=tracks
DB_USER=tracks
DB_PASS=$(mcookie)
WEBROOT=/var/www/tracks

# start mysql
service mysql start

# use default config template
cp $WEBROOT/config/site.yml.tmpl $WEBROOT/config/site.yml

# configure DB using db conf template
cp $WEBROOT/config/database.yml.tmpl $WEBROOT/config/database.yml
mysqladmin create $DB_NAME
mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* to $DB_USER@localhost IDENTIFIED BY '$DB_PASS'; flush privileges;"
sed -Ei "\|production| {n; :a; \|password:|! {N; ba;}; \
    s|(password:).*|\1 $DB_PASS|; \
    s|(^.*)# +(encoding:.*)|\1\2|; \
    :b; n; $! bb} " \
    $WEBROOT/config/database.yml
sed -i "\|username: |s|:.*|: tracks|" $WEBROOT/config/database.yml
sed -i '\|# encoding:|s|# ||' $WEBROOT/config/database.yml

cd $WEBROOT

rm .ruby-version

# fix broken dep - see https://github.com/TracksApp/tracks/blob/ruby31/Gemfile#L32
sed -i "\|^gem 'therubyracer',|s|'therubyracer'|'mini_racer'|" Gemfile

# install
export RAILS_ENV=production
bundle config set --local path 'vendor/bundle'
bundle config set --local without 'test development postgresql sqlite'
bundle update
bundle exec rake db:migrate

# configure permissions
mkdir -p $WEBROOT/tmp/cache
chown -R www-data:www-data $WEBROOT/tmp
mkdir -p $WEBROOT/public/uploads/csv
chown -R www-data:www-data $WEBROOT/public/uploads
mkdir -p /var/log/tracks
#chown -R www-data:www-data $WEBROOT/log
chown -R www-data:www-data /var/log/tracks
chmod 666 $WEBROOT/log/*

# precompile assets
bundle exec rake assets:precompile

# turnkey-credit (passenger substitute x2 bug)
cat >>$WEBROOT/app/assets/stylesheets/tracks.css.scss<<EOF
#turnkey-credit {
    font-family: Tahoma,Sans,Arial,Helvetica,Verdana,sans-serif;
    font-size: 11px;
    text-align: center;
    padding-top: 5px;
}
#turnkey-credit a {
    text-decoration: none;
}
EOF

TURNKEY_CREDIT="<div id='turnkey-credit'> <div> <a href='https://www.turnkeylinux.org/tracks'>Tracks Appliance</a> - Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a> </div> </div>"

FOOTER=$WEBROOT/app/views/shared/_footer.html.erb
sed -i "s|</div>|$TURNKEY_CREDIT\n</div>|" $FOOTER

service apache2 start

sleep 5

# create admin user & init app settings
TOKEN=$( curl -c /tmp/cookies.txt -s http://localhost/signup \
        | grep -o '<input type="hidden" name="authenticity_token" .* />' \
        | grep -o 'value=".*"' \
        | grep -o '".*"' \
        | tr -d \" )
curl -s -X POST -b /tmp/cookies.txt http://localhost/users \
        --data-urlencode "utf8=✓" \
        --data-urlencode "authenticity_token=${TOKEN}" \
        --data-urlencode "user%5Blogin%5D=${ADMIN_NAME}" \
        --data-urlencode "user%5Bpassword%5D=${ADMIN_PASS}" \
        --data-urlencode "user%5Bpassword_confirmation%5D=${ADMIN_PASS}"

rm -f /tmp/cookies.txt

# stop mariadb & apache2
service mariadb stop
service apache2 stop
